base_url: /guide-ko
title: LG Open Source Guide
lang: ko
description: LG Open Source Guide Korean version

remote_theme: LGE-OSS/jekyll-rtd-theme

top_link: "https://oss.lge.com/guide"
top_link_word: "English"

show_sorted: false
addons_branch: true

google:
  gtag: UA-181757464-1

addons:
  - github
  - i18n
  - plugins
  - analytics


# sort
readme_index:
  with_frontmatter: true

sass:
  style: compressed

exclude:
  - Makefile
  - Gemfile
  - Gemfile.lock

# optional plugins
plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions
