base_url: /guide_test
title: LG Open Source
lang: kor
description: LG Open Source Guide

remote_theme: rundocs/jekyll-rtd-theme

show_sorted: false
addons_branch: true

copyright:
  revision: true

addons:
  - github
  - i18n
  - plugins
  - analytics

# sort
readme_index:
  with_frontmatter: true

sass:
  style: compressed

exclude:
  - Makefile
  - Gemfile
  - Gemfile.lock

# optional plugins
plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions
